# the basic jekyll setup
source: .
destination: ./_site
layouts_dir: ./_layouts

# defining permalinks
permalink: :title
paginate_path: 'page:num'
repository: bullgit/bullgit.github.io
gems:
  - 'jekyll-github-metadata'
sass:
    style: compressed
