# defining permalinks for the blog
permalink: :title
paginate_path: 'page:num'

# using site.github in development
repository: bullgit/bullgit.github.io
gems:
  - 'jekyll-github-metadata'

# other settings
sass:
    style: compressed
