# defining permalinks for the blog
permalink: :title
paginate_path: 'page:num'
baseurl: /
# using site.github in development
repository: bullgit/bullgit.github.io
plugins:
  - 'jekyll-github-metadata'

# other settings
sass:
    style: compressed

# Exclude
exclude: [vendor]
